### ISSUE TITLE
希望获取数据集的具体格式规范

### ISSUE THREAD

**Issue by 854342681** [thunlp/explore-and-evaluate#4]
您好，我正在构建一个新的跨语言知识图谱数据集，想使用您的模型验证数据集的性能，可是不太清楚您数据集的所用格式规范，如三元组的token分别代表什么，可以请您提供一下数据集格式的规范吗？
谢谢！

**Comment by acharkq** [comment]
Hi, 感谢你对这个工作的关注, 你可以在[MuGNN](https://github.com/thunlp/MuGNN)的主页找到我的格式规范.

假如你还有问题, 欢迎你继续提问!

**Comment by 854342681** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 854342681** [comment]
收到，谢谢您的回复！

**Comment by 854342681** [comment]
您好，能再请教一下digit_data,att2id,attr2id_xx,id2atts和test_sr_ids_xx，分别如何构建的？具体来说digit_data中每列的含义及构建方法，att2id,attr2id_xx,id2atts属性选择的规则，test_sr_ids_xx的含义。
谢谢！

**Comment by acharkq** [comment]
你好, 感谢对我们工作的关注.

`digit_data` 这个文件在代码中并没有用到.

`att2id`和`id2atts` 都是对两个KG中所有的attribute的编号. `attr2id_xx` 是对单个KG中的attribute的编号. 这里的attribute没有经过特殊的规则选择. 

`test_sr_ids_xx` 文件可以参考`load_data.py`的197 -- 207行. 这里制造了不同比例的train/test split, 从而进行*Multi-Channel Graph Neural Network for Entity Alignment*文章中Figure3的ablation study. 但在这篇文章中没有用到.

**Comment by 854342681** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
