### ISSUE TITLE
执行 python train_subgraph.py --gpu_id 0 --channel Literal --dataset DBP15k/zh_en  出错了

### ISSUE THREAD

**Issue by JLei67** [thunlp/explore-and-evaluate#5]
![image](https://user-images.githubusercontent.com/63441816/159643833-e3c4275b-ef50-4fb8-8961-8e932c7eb989.png)
![image](https://user-images.githubusercontent.com/63441816/159644061-e4f8c8f3-6394-4cc9-8465-0e8a2cc27802.png)

为什么ent_feats_sr序号会是floattensor呢

**Comment by acharkq** [comment]
Hi, `ent_seed_sr` 变量应该是整数变量, 而不是浮点数. 这可能是因为pytorch版本更新导致的. 你可以将这行改动为
```
sr_seed_feats = ent_feats_sr[ent_seed_sr.long()]
```
